### ISSUE TITLE
Make length measures play nicely with Compose

### ISSUE THREAD

**Issue by aviks** [shashi/Escher.jl#10]
If I change the plot command in `plot.jl` to the following

```julia
plot([x -> sin(x + phase), x -> cos(x + phase)], 0, 6, 
                xintercept=[-.55, +.5], Geom.vline(color="purple", size=0.2mm))
```

I get the following error on the console: 

```
Error handling websocket connection:
type: typeassert: expected Union(Measure{S,T},Nothing), got Length{:mm}
 in anonymous at /Users/aviks/.julia/v0.3/Canvas/examples/plot.jl:9
 in main at /Users/aviks/.julia/v0.3/Canvas/examples/plot.jl:8
 in uisocket at /Users/aviks/.julia/v0.3/Canvas/bin/canvasd:111
 in anonymous at /Users/aviks/.julia/v0.3/Mux/src/Mux.jl:15
 in anonymous at /Users/aviks/.julia/v0.3/Mux/src/Mux.jl:8
 in splitquery at /Users/aviks/.julia/v0.3/Mux/src/basics.jl:28
 in anonymous at /Users/aviks/.julia/v0.3/Mux/src/Mux.jl:8
 in wcatch at /Users/aviks/.julia/v0.3/Mux/src/websockets.jl:12
 in anonymous at /Users/aviks/.julia/v0.3/Mux/src/Mux.jl:8
 in todict at /Users/aviks/.julia/v0.3/Mux/src/basics.jl:21
 in anonymous at /Users/aviks/.julia/v0.3/Mux/src/Mux.jl:12 (repeats 2 times)
 in anonymous at /Users/aviks/.julia/v0.3/Mux/src/Mux.jl:8
 in anonymous at /Users/aviks/.julia/v0.3/Mux/src/server.jl:36
 in handle at /Users/aviks/.julia/v0.3/WebSockets/src/WebSockets.jl:287
 in on_message_complete at /Users/aviks/.julia/v0.3/HttpServer/src/HttpServer.jl:296
 in on_message_complete at /Users/aviks/.julia/v0.3/HttpServer/src/RequestParser.jl:99
 in http_parser_execute at /Users/aviks/.julia/v0.3/HttpParser/src/HttpParser.jl:106
 in add_data at /Users/aviks/.julia/v0.3/HttpServer/src/RequestParser.jl:148
 in process_client at /Users/aviks/.julia/v0.3/HttpServer/src/HttpServer.jl:267
 in anonymous at task.jl:340
```

If I change the `size=0.2mm` to `size=0.2em`, then the error becomes:
 `type: typeassert: expected Union(Measure{S,T},Nothing), got Length{:em}`

**Comment by shashi** [comment]
Yeah I know about this. Canvas and Compose export length consts of the same
name. No idea what to do about that yet. Maybe we could separate this stuff
into a Measures.jl library and use it in both. Cc @dcjones

For now you can use Gadfly.mm or Canvas.mm, whichever is appropriate

**Comment by aviks** [comment]
OK, thanks, that helps.

**Comment by dcjones** [comment]
> Maybe we could separate this stuff into a Measures.jl library and use it in both. Cc @dcjones

That would be appealing if we can reconcile the Compose and Canvas definitions of things. Though, at one point we wanted to try to combine the SIUnits and Compose definitions of things like `inch` and `mm`, but decided it didn't make a lot of sense.

The measures in Compose differ from Canvas in that they need to represent sums of absolute and relative unit types: like `3mm + 0.5cx`. I'm not sure the best way to make that work with the more obvious definitions in Canvas.

**Comment by shashi** [comment]
Yeah, that way they are different. I think `vh` and `vw` would be the `cy` `cx` analog of CSS. Will need some web component pixie dust to make the arithmetic between absolute and relative units work, but not impossible.

**Comment by shashi** [comment]
Oh look! http://dev.w3.org/csswg/css-values-3/#calc-notation There is a spec to do exactly this! With OK browser support: http://caniuse.com/#feat=calc

**Comment by dcjones** [comment]
Perfect! That's much easier that having to compute everything dynamically in javascript. So in a unified measure package, I suppose `cx`/`cy` (which I'm open to renaming) would be kept separate, but when applied in the CSS context just added to viewport measures (`vw`/`vh`)?

**Comment by shashi** [comment]
Actually I realized this is more tricky. `vw`, `vh` represent the size of the screen (except when they don't :|) and `%` measures are also sadly cannot represent `cx` *and* `cy`. 

But, all is not lost. I found out about http://gridstylesheets.org/ I have no idea though if it can be used in Polymer components.

**Comment by shashi** [comment]
How about `cx` and `cy` being Compose-specific. This library can contain them, but Escher won't be using them. I think this is a reasonable middle-ground

Also, `pc` is a unit of length in itself and is different from percentage. In Escher I call percentage `cent`
