### ISSUE TITLE
 push! called when another signal is still updating.

### ISSUE THREAD

**Issue by Ismael-VC** [shashi/Escher.jl#100]
I'm using Julia version `v"0.4.0"` and Escher ` 0.2.0`. I'm getting this error when running `Escher.jl/examples/boids.jl`

```
ERROR (unhandled task failure): push! called when another signal is still updating.
 in push! at C:\Users\Peter\.julia\v0.4\Reactive\src\Reactive.jl:340
 in anonymous at C:\Users\Peter\.julia\v0.4\Reactive\src\timing.jl:36
 [inlined code] from stream.jl:693
 in anonymous at task.jl:689
```

* Related issue from JuliaGL/GLVisualize.jl#26

**Comment by Ismael-VC** [comment]
Seems that `Reactive` **831a4703dbed75f02a681963e67020f660af193a** solves this.

**Comment by randyzwitch** [comment]
Looks like there was a resolution to this, so closing
