### ISSUE TITLE
custom widgets?

### ISSUE THREAD

**Issue by datnamer** [shashi/Escher.jl#101]
Hi,

Is it possible to add custom elements/JS libraries as escher widgets?

Thanks

**Comment by rohitvarkey** [comment]
Yeah. See https://github.com/shashi/Escher.jl/pull/74.

You need to create a `assets` folder in your package directory and put files there. And then a `push!(window.assets, (<Pkg name>, <asset name>))` will push the asset file to the window. 

Is that what you were looking for?

**Comment by datnamer** [comment]
Yea thanks! Then how do I work with it? Do I need to wrap it with custom js?

**Comment by NOTtheMessiah** [comment]
It would be served from *http://localhost:5555/pkg/\<Pkg name\>/\<filename\>*
To use it within a document, you need to use the `@api` macro to make a type constructor, and a render method on that type that creates a [Patchwork](https://github.com/shashi/Patchwork.jl) Element. See src/library for examples.

**Comment by randyzwitch** [comment]
Closing, since there was resolution. Related: #26
