### ISSUE TITLE
Examples not working on master

### ISSUE THREAD

**Issue by amellnik** [shashi/Escher.jl#106]
Running any example on the current master is giving me 

```
MethodError: `convert` has no method matching convert(::Type{Reactive.Signal{T}}, ::Type{Escher.Tile}, ::Escher.Empty)
This may have arisen from a call to the constructor Reactive.Signal{T}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{Reactive.Signal{T}}, !Matched::Reactive.SignalSource)
  convert{T}(::Type{T}, !Matched::T)
```

I'm starting it from ijulia and there's no mention of a line number or similar.

**Comment by shashi** [comment]
The master branch needs the master branch of Reactive.

**Comment by amellnik** [comment]
Ah whoops, I had assumed that checking out the master and then running Pkg.update() would have taken care of this sort of thing.  I'll hold off until they have tagged versions.  Thanks -A

**Comment by dioptre** [comment]
+1 This still doesnt work for me and I'm on latest

**Comment by shashi** [comment]
@dioptre can you paste your Pkg.status() output?
