### ISSUE TITLE
Default table style?

### ISSUE THREAD

**Issue by amellnik** [shashi/Escher.jl#107]
The default table style at the moment is a bit sparse.  Right now 

``` julia
DataFrame(A = [1,2], B=["A", "D"])
```

renders as 

![image](https://cloud.githubusercontent.com/assets/7132414/11385357/cffec02a-92cc-11e5-8108-326ab135aba6.png)

I assume Escher would like something that looks a bit more classy than the normal writemime output that's used in ijulia and similar, but some lines and padding might be nice.

**Comment by shashi** [comment]
I agree we need better defaults here.

You can create a `DataFrame` of padded / bordered tiles to achieve this now.

**Comment by amellnik** [comment]
Closing - outdated.
