### ISSUE TITLE
Path error when attempting to launch server

### ISSUE THREAD

**Issue by sdacek** [shashi/Escher.jl#108]
When attempting to launch the server I get the following error

```ERROR: LoadError: LoadError: LoadError: InitError: UndefVarError: Dacek/.julia/v0.4/MacroTools/src/utils.jl not defined```

The correct path is  /Users/Stephen_Dacek/.julia/v0.4/MacroTools/src/utils.jl  and the file exists.

**Comment by rohitvarkey** [comment]
Can you try doing `using MacroTools` in a REPL and see if that works?

**Comment by sdacek** [comment]
MacroTools loads without error

**Comment by sdacek** [comment]
Did some quick digging. It is a bug in the Requires Package. I cannot load it and that error results

**Comment by shashi** [comment]
I could fix it by removing the call to `__precompile__()` at the beginning of `Requires/src/Requires.jl` file

**Comment by randyzwitch** [comment]
Per @sdacek, a bug in the Requires package, so closing here
