### ISSUE TITLE
"import Escher" fails

### ISSUE THREAD

**Issue by omalled** [shashi/Escher.jl#115]
I haven't been able to get Escher working since doing a Pkg.update() recently. Even "import Escher" fails (see below).

```
julia> Pkg.status("Escher")
 - Escher                        0.3.0

julia> Pkg.status("Reactive")
 - Reactive                      0.3.0

julia> import Escher
ERROR: LoadError: InitError: UndefVarError: __inits__ not defined
 in __init__ at /homedir/.julia/v0.4/Escher/src/Escher.jl:67
 in include at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
during initialization of module Escher
while loading /homedir/.julia/v0.4/Escher/src/Escher.jl, in expression starting on line 66

julia> VERSION
v"0.4.3"
```
I also tried doing a Pkg.checkout("Escher") and Pkg.build("Escher") to try to get something more recent, but that produced the same result. Any idea what's up?

Escher is fantastic, BTW!

**Comment by ranjanan** [comment]
I think this could be a problem in the `Requires` package.

**Comment by ranjanan** [comment]
I think changing `Requires.@init` to `Requires.@init Escher` [here](https://github.com/shashi/Escher.jl/blob/master/src/Escher.jl#L67) fixes this.

**Comment by Evizero** [comment]
related: https://github.com/shashi/Escher.jl/commit/5a0e84d81c9a2eb77687d9eba1590c45aedf55fd#commitcomment-15703555
