### ISSUE TITLE
hbox not working properly

### ISSUE THREAD

**Issue by omalled** [shashi/Escher.jl#122]
The following code uses `hbox`, but the browser displays it as if I had used `vbox`:

```
function main(window)
	hbox(plaintext("foo"), plaintext("bar"))
end
```

That is, the browser displays something like

foo
bar

with "foo" above "bar" rather than something like

foobar

with "foo" to the left of "bar". I am using julia 0.4.3 and Escher 0.3.1 on a Mac and I tried viewing in both Firefox and an up-to-date Chrome.

**Comment by randyzwitch** [comment]
Confirmed. Seems like it's a problem with `plaintext`; doing a similar example from the documentation works:

```julia
function main(window)
    push!(window.assets, "tex")

    txt = tex("T = 2\\pi\\sqrt{L\\over g}")
    txt1 = fontcolor("#499", txt)
    txt2 = fontcolor("#499", txt)
    txt3 = fillcolor("#eeb", txt2)

    hbox(txt, txt1, txt2, txt3)
end
```
<img width="341" alt="screen shot 2016-04-12 at 4 52 54 pm" src="https://cloud.githubusercontent.com/assets/2762787/14475237/07e3481a-00cf-11e6-8f09-b3a975632ec6.png">

**Comment by rohitvarkey** [comment]
Interestingly, `hbox(hbox(plaintext("foo"), plaintext("bar")))` works. 

When `hbox` is used at the top the div doesn't seem to get the `flow horizontal` class added to it. I'll take a look at this tomorrow.

**Comment by shashi** [comment]
The problem is patching the initial `div` that exists before rendering anything is not quite working. So if you put your whole app in a container (`pad(0em) e.g.`) it should look like it should. I'm trying to figure out what's up.

**Comment by shashi** [comment]
Okay traced this back to https://github.com/shashi/Patchwork.jl/commit/6cc99119024ef64459076bf6b41e482931391832

I accidentally reversed some changes while building the Patchwork build.js file. (I will need to fork virtual-dom to prevent this.)
