### ISSUE TITLE
Homepage out of date

### ISSUE THREAD

**Issue by ryanmjacobs** [shashi/Escher.jl#123]
Just a minor quip; it's 2016 now.

> A web server for **2015**. Escher's built-in web server allows you to create interactive UIs with very little code. It takes care of messaging between Julia and the browser under-the-hood. It can also hot-load code: you can see your UI evolve as you save your changes to it.

**Comment by randyzwitch** [comment]
Since we're highlighting changes, Vega.jl and probably vegalite also work with Escher.

**Comment by randyzwitch** [comment]
Closing since PR is in
