### ISSUE TITLE
Display an image quicker than using spy()

### ISSUE THREAD

**Issue by cmey** [shashi/Escher.jl#127]
Currently I use `spy()` from Gadfly, it works, but it's slow. Is there a faster alternative?

I've tried `bitmap()` from Compose, but it doesn't render ([separate issue](https://github.com/shashi/Escher.jl/issues/128)).

**Comment by shashi** [comment]
Is your sparse matrix really big?

If so,you should render the image as using the PNG backend.

You can do it by using

```
drawing(PNG(5inch, 5inch), spy(...))
```
instead of just `spy(...)`

**Comment by shashi** [comment]
Does it work? I'm closing this issue since it's the issue should be addressed by Patchwork or by Gadfly.
