### ISSUE TITLE
bitmap() from Compose doesn't render

### ISSUE THREAD

**Issue by cmey** [shashi/Escher.jl#128]
I've tried to display `bitmap("test", rand(UInt8,9), 0, 1, 3, 3, :image)`, but it doesn't render. Instead, it prints:
```
Compose.Form{Compose.BitmapPrimitive{Tuple{Measures.Length{:cx,Int64},Measures.Length{:cy,Int64}},Measures.Length{:cx,Int64},Measures.Length{:cy,Int64}}}([Compose.BitmapPrimitive{Tuple{Measures.Length{:cx,Int64},Measures.Length{:cy,Int64}},Measures.Length{:cx,Int64},Measures.Length{:cy,Int64}}("test",UInt8[0x03,0xe8,0xda,0xf3,0x36,0x23,0x9c,0x36,0x8e],(0cx,1cy),3cx,3cy)],:image)
```
in the webpage.

**Comment by shashi** [comment]
Yeah, this is because the Patchwork backend doesn't support bit maps in a compose image...

**Comment by cmey** [comment]
I've opened an issue there (https://github.com/shashi/Patchwork.jl/issues/15).

**Comment by jingpengwu** [comment]
Just find that there is a `image` tile, and it works pretty well. I tested both url and Images.imread.
http://escher-jl.org/content-api.html
