### ISSUE TITLE
Better package name?

### ISSUE THREAD

**Issue by ViralBShah** [shashi/Escher.jl#13]
@shashi @aviks As we discussed before, Canvas invokes many different meanings in one's mind. I liked @shashi 's suggestion of calling this package Escher.jl.

**Comment by aviks** [comment]
+1 for Escher. Evocative and relevant, I feel.

**Comment by aviks** [comment]
ping!

**Comment by shashi** [comment]
I like Escher too. It sets the right tone for the kinds of things you can make with this package. If Escher was a programmer, he'd probably love Lisps, and Julia is as good as any.

I'm going to rename all the things and make a push tonight.

**Comment by aviks** [comment]
Yay!
