### ISSUE TITLE
Performance in Firefox on OS X?

### ISSUE THREAD

**Issue by tlnagy** [shashi/Escher.jl#139]
The performance of a lot of the examples is pretty awful in Firefox 45.0.2 on OS X 10.11. Chrome fares a lot better. `boids.jl` is especially bad on Firefox.

**Comment by randyzwitch** [comment]
Can you quantify "awful"? I noticed yesterday that a lot of pre-compilation takes place, then things worked better. But I always use Chrome

**Comment by tlnagy** [comment]
It's even after precompilation takes place because that prevents the page from loading. But it could be something with my Firefox installation that is borked because of this: https://github.com/johnmyleswhite/Vega.jl/issues/123. I'll try and troubleshoot and see.

**Comment by randyzwitch** [comment]
@tlnagy do you feel this is still an issue? If so, we can keep it open, but as it sits now, it's pretty tough to quantify.
