### ISSUE TITLE
Plotting doesn't work on Firefox on OS X

### ISSUE THREAD

**Issue by tlnagy** [shashi/Escher.jl#140]
Plotting doesn't seem to work on Firefox 45.0.2, works fine in Chrome 49:

<img width="584" alt="screen shot 2016-04-12 at 15 03 36" src="https://cloud.githubusercontent.com/assets/1661487/14477095/ad9c70b0-00c0-11e6-94a3-c88d542e9aec.png">

(Firefox is in safe-mode, all plugins disabled)

**Comment by shashi** [comment]
This is a bug in Patchwork (e.g. Gadfly+ComposeDiff+IJulia does not work in Firefox either). @dcjones @yeesian and I took a look at this but have failed so far to do anything about it. But it will be a very useful thing to chase down

**Comment by randyzwitch** [comment]
Per https://github.com/johnmyleswhite/Vega.jl/issues/123, could this just be a local error or an operating-system-specific error?

**Comment by shashi** [comment]
LOL, that's interesting. I will have to try it out.
