### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by montyvesselinov** [shashi/Escher.jl#142]
Error handling websocket connection:
MethodError: `start` has no method matching start(::Reactive.Signal{Any})
 in foreach at /Users/monty/.julia/v0.4/Compat/src/Compat.jl:928
 in anonymous at /Users/monty/.julia/v0.4/Escher/src/cli/serve.jl:161
 in anonymous at /Users/monty/.julia/v0.4/Mux/src/Mux.jl:15
 in anonymous at /Users/monty/.julia/v0.4/Mux/src/Mux.jl:8
 in splitquery at /Users/monty/.julia/v0.4/Mux/src/basics.jl:28
 in anonymous at /Users/monty/.julia/v0.4/Mux/src/Mux.jl:8
 in wcatch at /Users/monty/.julia/v0.4/Mux/src/websockets_integration.jl:12
 in anonymous at /Users/monty/.julia/v0.4/Mux/src/Mux.jl:8
 in todict at /Users/monty/.julia/v0.4/Mux/src/basics.jl:21
 in anonymous at /Users/monty/.julia/v0.4/Mux/src/Mux.jl:12 (repeats 2 times)
 in anonymous at /Users/monty/.julia/v0.4/Mux/src/Mux.jl:8
 in anonymous at /Users/monty/.julia/v0.4/Mux/src/server.jl:38
 in handle at /Users/monty/.julia/v0.4/WebSockets/src/WebSockets.jl:382
 in on_message_complete at /Users/monty/.julia/v0.4/HttpServer/src/HttpServer.jl:393
 in on_message_complete at /Users/monty/.julia/v0.4/HttpServer/src/RequestParser.jl:104
 in http_parser_execute at /Users/monty/.julia/v0.4/HttpParser/src/HttpParser.jl:92
 in process_client at /Users/monty/.julia/v0.4/HttpServer/src/HttpServer.jl:365

**Comment by shashi** [comment]
Which example are you trying to run? I'm unable to reproduce this easily. It looks like you're using Julia 0.5 although the package is installed in 0.4. Are you using Escher master?

**Comment by rohitvarkey** [comment]
This is solved on Escher master. Dup of https://github.com/shashi/Escher.jl/issues/138

@shashi Let's tag a new release?

**Comment by montyvesselinov** [comment]
Pkg.checkout("Escher") resolved the problem. Thank you very much!

**Comment by shashi** [comment]
tagged a new release.
