### ISSUE TITLE
UndefVarError: px not defined

### ISSUE THREAD

**Issue by montyvesselinov** [shashi/Escher.jl#143]
WARNING: both Compose and Escher export "px"; uses of it in module Main must be qualified
Error handling websocket connection:

Any suggestions how to address this?

**Comment by rohitvarkey** [comment]
Just qualifying the use of `px` with `Escher.px` or `Compose.px` as according to your requirement will work.

**Comment by montyvesselinov** [comment]
Old Compose! Updating compose fixed the problem.
