### ISSUE TITLE
Slider while dragging

### ISSUE THREAD

**Issue by mfalt** [shashi/Escher.jl#147]
I'm trying to make some additions but am struggling to understand the code, and I received no help on gitter.im (and the webpage http://escher-jl.org/behavior-api.html is failing under firefox).
I want to add an option to make the slider update while the user is dragging. It is possible to do
```julia
wrapbehavior(s::Slider) =
    intent(ToType{eltype(s.range)}(), hasstate(s, attr="immediateValue", trigger="immediate-value-change"))
```
in `src/library/widgets.jl`, but then it doesn't trigger on a normal "change". I am not able to understand how to add multiple triggers and how to then handle the data, does anyone have any pointers?

**Comment by shashi** [comment]
replied on gitter. I think we need some enhancement to hasstate to support this. it is possible to use `collector` to get this now I think.

**Comment by izaid** [comment]
I have made an attempt to fix this with https://github.com/shashi/Escher.jl/pull/178
