### ISSUE TITLE
multiple subscriptions / nested maps

### ISSUE THREAD

**Issue by StreetLevel** [shashi/Escher.jl#148]
Hi Sashi,
I have some problems creating some sliders, whose values and ranges depend on each other.
I would be very nice if you could help me out.
Here is a minimal example:
```julia
main(window) =  begin
	push!(window.assets,"widgets")
	s1 = Signal(1)
	map(s1) do n1
		vbox1 = (
			hbox(slider(1:5) >>> s1)
		)
		s2 = Signal(n1)
		vbox2 = map(s2) do n2
			vbox(
				hbox(slider(n1:10) >>> s2),
				hbox("s1 = $n1"),
				hbox("s2 = $n2")
			)
		end
		vbox(
			vbox1,
			vbox2
		) 
	end
end
```

The problem is: After i once have changed the first slider, the second slider isn't subscribed to the second signal anymore. Is there a way to make this example work?

Best, Max

**Comment by shashi** [comment]
Where are you using `s2` after creation? Since it is in another `map` expression, it will go out of scope and be replaced with another `s2` once `s1` updates.... You could instead move `s2` out and map over both `s1` and `s2`.

```julia

main(window) =  begin
    push!(window.assets,"widgets")
    s1 = Signal(1)
    s2 = Signal(n1)
    map(s1, s2) do n1
        vbox1 = (
            hbox(slider(1:5) >>> s1)
        )
        vbox2 =  vbox(
                hbox(slider(n1:10) >>> s2),
                hbox("s1 = $n1"),
                hbox("s2 = $n2")
         )

        vbox(
            vbox1,
            vbox2
        ) 
    end
end
```

**Comment by StreetLevel** [comment]
Ok, thank you. I was thinking way to complicated.
I'm closing this one.
