### ISSUE TITLE
How to launch Escher executable on Windows?

### ISSUE THREAD

**Issue by neilpanchal** [shashi/Escher.jl#149]
I added the directory - C://Users/Username/.julia/v0.4/Escher/bin/escher to the PATH environment variable. When I use windows command line and try to run escher, it gives me an error "escher is not a recognized as an internal or external command, operable program or batch file".

I think the documentation is only for linux/macosx and not applicable to windows. Please provide advice and I will update the documentation.

- Neil

**Comment by StreetLevel** [comment]
I think the directory that should be added to the path is  "C://Users/Username/.julia/v0.4/Escher/bin/". But anyway this script won't work with windows. What you could do is write your own batch or call escher_serve() from julia, manually.
To write your own batch you just have to create a julia file e.g.: 
start_escher_server.jl:
```julia
using Escher
include(Pkg.dir("Escher", "src", "cli", "serve.jl"))
escher_serve()
```
and then just write a batch which calls `julia start_escher_server.jl`. That should do the trick.

Best, Max

**Comment by rohitvarkey** [comment]
@neilpanchal Please re-open if this is still a problem.
