### ISSUE TITLE
Specify a base directory

### ISSUE THREAD

**Issue by aviks** [shashi/Escher.jl#15]
Currently, canvasd only serves .jl files out of its current working directory. 

There should be of specifying a base directory from which to serve files. Forward relative paths from this directory should be followed. Backward relative paths should not be allowed. 

It may be worth thinking about a long term configuration format. Command line flags only? INI/Toml files? JSON?

**Comment by shashi** [comment]
I was thinking this would be a command line flag. say `--base`, what are some reasons one would need a configuration file?

The list of features would be:

- [ ] server should be brought up if `--serve` is specified, optionally allow a port number
- [ ] `--blink` should open up an Atom shell window with the UI
- [ ] `--compile` should output static HTML (warn in the case of a `Signal{Tile}`, but compile the initial value anyway.
- [ ] `--docs <pkgname>` start serving documentation from a package, can include interactive UIs too
- [ ] rename canvasd to canvas

**Comment by aviks** [comment]
command line flags are fine. One reason to use a config file would be if I want to start a cluster of canvasd processes, I could ensure consistency of configuration using a file. Basically, version and store the config file, rather than the script that starts the processes. But its not a big concern.

**Comment by shashi** [comment]
you should now be able to use `bin/escher --serve --dir "whatever-directory"`

**Comment by aviks** [comment]
Cool, thanks!
