### ISSUE TITLE
http://escher-jl.org/ blanks in few seconds..

### ISSUE THREAD

**Issue by PallHaraldsson** [shashi/Escher.jl#165]
This may have been fixed in the last few days (happened within a month) or not and I just didn't wait long enough.

I do not remember this from the early days, but has been like this for some months now.

I'm not sure if it reflects on Escher.jl itself (the webpage built with it?) or just falsely(?) implies it's broken..

**Comment by PallHaraldsson** [comment]
At least the problem is in http://escher-jl.org/layout2-api.html and other sub-pages of the README.

I hadn't looked at those pages before, and it's pretty obvious, happens under a second. [At the main page, it happend before, if not now, in I guess longer time, less then 5.]

Testing now in Firefox (have before in Chrome, and others have confirmed for me before for their machines).

**Comment by lassehp** [comment]
I was looking at Julia as a possible new interesting language to learn, and came to escher-jl.org from the Julia page on Wikipedia. I was puzzled when the page first displayed unstyled, then a (beautiful btw) style was applied, only to have the window blanked out few seconds later.

Seeing that this issue has been open for quite some time, is not very encouraging to a prospective user.
