### ISSUE TITLE
Mux not found in path

### ISSUE THREAD

**Issue by randyzwitch** [shashi/Escher.jl#17]
What is this trying to get me to do?

```julia

HQSML-146932:examples rzwitc200$ ../bin/escherd
ERROR: LoadError: ArgumentError: Mux not found in path
 in require at ./loading.jl:49
 in include at ./boot.jl:250
 in include_from_node1 at loading.jl:129
 in process_options at ./client.jl:308
 in _start at ./client.jl:407
while loading /Users/rzwitc200/.julia/v0.3/Escher/bin/escherd, in expression starting on line 4

```

**Comment by shashi** [comment]
Have you installed Mux.jl ? `Pkg.clone("git@github.com:one-more-minute/Mux.jl.git")`

There are a bunch of things you need to do right now to set this up. The [README](https://github.com/shashi/Escher.jl#readme) should cover this.

**Comment by randyzwitch** [comment]
Yes, I went through the README, installed all the packages and the above is the result I got back using Julia 0.3.7. If Mux is written in Julia, how can it be in my path?

**Comment by shashi** [comment]
Mux should go in `~/.julia/v0.3/Mux/` directory. Also `~/.julia/v0.3/Mux/src/Mux.jl` must be present and should contain a module called Mux. Hmm, I wonder what is happening here. I don't see any problem with https://github.com/one-more-minute/Mux.jl/blob/master/src/Mux.jl

**Comment by randyzwitch** [comment]
```julia
HQSML-146932:src rzwitc200$ pwd
/Users/rzwitc200/.julia/v0.3/Mux/src
HQSML-146932:src rzwitc200$ ls
Mux.jl		examples	server.jl
basics.jl	routing.jl	websockets.jl
```

**Comment by shashi** [comment]
Okay.... What is your `/usr/bin/env julia` (this is the shell used by `escherd`) ? Is that where Mux is installed?

**Comment by shashi** [comment]
From your outputs, it does look like everything is alright. I'm really out of ideas about what is happening here, :-o

**Comment by randyzwitch** [comment]
Fixed that error...`julia` at my CLI referred to 0.4; pre-pending 0.3 fixed it. There were two more pkg errors, I'll submit a PR to README. I got the example to finally work, it's just a picture of the Golden Ratio squares, right?

**Comment by shashi** [comment]
Yes, `examples/layout.jl` that's not Golden Ratio squares I think, it's like a depiction of 1/2 + 1/4 + 1/8 +..... But if you check out docs/guide/layout.jl you can see some docs. You will need to run escherd from docs/guide/ to do that. Also, heads up: files containing gadfly plots might take forever to load.

**Comment by shashi** [comment]
I just moved docs/guide/layout.jl to docs/layout-guide.jl so now there are only 2 places you can run escherd: examples/ and docs/
