### ISSUE TITLE
Unable to start Escher package

### ISSUE THREAD

**Issue by nandu116** [shashi/Escher.jl#174]
Hi, I am using latest version of Ubuntu 16.04.
I have installed Julia v0.4.5 and added the package Escher.jl from REPL.
After this I have a run a test code published on escher-jl.org and received an error.

**Code:**
_julia> using Escher --Success
julia> include(Pkg.dir("Escher", "src", "cli", "serve.jl"))  -- Failed with below error and did not proceed further.
julia> cd(Pkg.dir("Escher", "examples")) # or any other directory
julia> escher_serve()_

**ERR**
_julia> include(Pkg.dir("Escher", "src", "cli", "serve.jl"))
WARNING: could not import Mux.@d into Main
ERROR: LoadError: UndefVarError: @d not defined
while loading /home/n/.julia/v0.4/Escher/src/cli/serve.jl, in expression starting on line 67_

**Comment by datnamer** [comment]
Do you have mux installed?
