### ISSUE TITLE
How to use mongo commands in escher.jl?

### ISSUE THREAD

**Issue by nandu116** [shashi/Escher.jl#175]
Hi, I have created below sample code to display mongo collection in browser but could not succeed. Can someone identify where am I doing wrong?
```julia
import Escher: @api, render
using Mongo,LibBSON, FactCheck

cli = MongoClient("mongodb://localhost:64116")
org = MongoCollection(cli, "FFC", "Org")
stack = find(org, Dict())

app = 
for doc in stack
  println(doc)
end

main(window) = begin
    push!(window.assets, "layout2")
    push!(window.assets, "icons")
    push!(window.assets, "widgets")

    t, p = wire(tabs([hbox(icon("home"), hskip(1em), "Home"),
                      hbox(icon("info-outline"), hskip(1em),  "Notifications"),
                      hbox(icon("info"), hskip(1em), "About")]),
                pages([app, "NO Notifications", "About"]), :tabschannel, :selected)

    vbox(toolbar(["FFC", flex(), iconbutton("face")]),
         maxwidth(116em, t),
         Escher.pad(1em, p))
end
```
edit: formatting

**Comment by shashi** [comment]
What should `app` be? in your case it will be `nothing` because a for loop always returns `nothing`. You might want to use `map` instead.

You don't need `import Escher: @api, render` or `using FactCheck`

**Comment by nandu116** [comment]
Thank you, shashi, it works.
Even though, we use "\n", I don't see a carriage return applied, all the docs get piled up. Any work around for this?

**Comment by shashi** [comment]
`vbox(map(string, stack))` should do it. Or  `vbox(intersperse(vskip(1em), map(string, stack)))` to give some space between them.

**Comment by nandu116** [comment]
perfect vbox(map(string, stack)) works for me.
Thanks for the quick solution.
