### ISSUE TITLE
Gadfly plotting is not working

### ISSUE THREAD

**Issue by izaid** [shashi/Escher.jl#181]
Gadfly appears to be broken, at least for me on Julia 0.4. Just using the plotting.jl example in Escher fails for me with the following error:

```
MethodError: `<<` has no method matching <<(::Patchwork.Elem{:svg,:text}, ::Text{ASCIIString})
Closest candidates are:
  <<(::Any, !Matched::Int64)
  <<(::Any, !Matched::Integer)
  <<{ns,tag}(::Patchwork.Elem{ns,tag}, !Matched::AbstractArray{T,N})
```

**Comment by phillc73** [comment]
Similar, but slightly different, error for me with plotting.jl example file:

```
MethodError: `drawing` has no method matching drawing(::Measures.Length{:mm,Float64}, ::Measures.Length{:mm,Float64}, ::Gadfly.Plot)
Closest candidates are:
  drawing(::Any, ::Any)
 in anonymous at /home/phillc/.julia/v0.4/Escher/src/cli/serve.jl:170
 in anonymous at /home/phillc/.julia/v0.4/Mux/src/Mux.jl:15
```
I have Julia 0.4.6 installed on Debian Testing.

**Comment by shashi** [comment]
@phillc73 You need to install a package called `ComposeDiff` for Gadfly to work with Escher. I believe @izaid's issue happens even after installing it. @izaid are you on the latest release of Patchwork and ComposeDiff?

**Comment by izaid** [comment]
@shashi I'm on the master of Patchwork.jl and the latest release of ComposeDiff.jl. Just double-checked everything, the error persists.

**Comment by phillc73** [comment]
@shashi Thanks. I fixed that issue. However, now I simply have a blank page. I'll start a new issue to keep things cleaner.

**Comment by slhuissier** [comment]
I get the same error as @izaid in julia-0.4.5. Has the issue been fixed?
