### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by rudimk** [shashi/Escher.jl#21]
Trying to experiment with using Escher for building a data dashboard. Would love some docs. Conversely, if you need a bit of help with building the docs itself, I can fork the repo and work on a ```gh-pages``` branch.

**Comment by shashi** [comment]
Hey rudi!

If you run `escherd` from docs/ directory, you should get to see the current state of the docs. (visit localhost:8000/<file-from-docs>.jl) My aim have separate user guide (pretty much for each file in the source tree) and API docs, and also a good tutorial, and eventually compile to static html pages and serve via github pages. (the compilation is not yet implemented, but is straightforward)

I am working on the documentation myself right now, any contributions will be much appreciated!

**Comment by rudimk** [comment]
Hey Shashi!

Sounds good. I'll go through the docs directory, and then probably figure out how to help with them. Thanks!

**Comment by ViralBShah** [comment]
Having static docs on an Escher homepage and a nice README is a must anyways.

**Comment by shashi** [comment]
defer to #26
