### ISSUE TITLE
macro api defines types in a local scope 

### ISSUE THREAD

**Issue by NOTtheMessiah** [shashi/Escher.jl#24]
When i remove the `@doc` calls in the return expression of `macro api`

    macroexpand(quote @api test => TestType1 begin
        arg(a::FloatingPoint)
    end end)

results in

    begin 
        immutable TestType1
            a::FloatingPoint
        end
        test(#445#a) = TestType1(#445#a)
    end

but normally, it expands to this

    begin 
        immutable TestType1
            a::FloatingPoint
        end
        begin  # /home/brian/.julia/v0.3/Docile/src/Legacy/atdoc.jl, line 140:
            begin  # /home/brian/.julia/v0.3/Docile/src/Legacy/atdoc.jl, line 9:
                if Docile.Legacy.!(Docile.Legacy.isdefined(:__DOCILE_STRINGS__)) # line 10:
                    const __DOCILE_STRINGS__ = Docile.Legacy.ObjectIdDict() # line 11:
                    const __DOCILE_METADATA__ = Docile.Legacy.ObjectIdDict() # line 12:
                    Docile.Legacy.nothing
                end
            end # line 141:
            #481#old = if isdefined(:test)
                    (Docile.Legacy.Set{Docile.Legacy.Method})(Docile.Legacy.methods(test))
                else 
                    (Docile.Legacy.Set{Docile.Legacy.Method})()
                end # line 142:
            test(#480#a) = TestType1(#480#a) # line 143:
            for #482#m = Docile.Legacy.setdiff((Docile.Legacy.Set{Docile.Legacy.Method})(Docile.Legacy.methods(test)),#481#old) # line 144:
                (Docile.Legacy.metadata())[#482#m] = Docile.Legacy.data(#482#m,("",[:typ=>:TestType1,:name=>:test,:args=>{{:type=>:FloatingPoint,:curried=>false,:coerced=>true,:kwarg=>false,:name=>:a}}]); category=:method,codesource=(336,""),code=$(Expr(:copyast, :(:(test(#480#a) = TestType1(#480#a))))))
            end # line 150:
            test
        end
    end

 `eval(ans)` results in

`error compiling anonymous: type definition not allowed inside a local scope
while loading In[15], in expression starting on line 1`

**Comment by shashi** [comment]
Oh, so it has to do with the `@doc` macro.
