### ISSUE TITLE
 ~/.julia/Escher/bin/escher --serve unresponsive and error running tests

### ISSUE THREAD

**Issue by maacl** [shashi/Escher.jl#30]
Nothing is served using:

    ~/.julia/Escher/bin/escher --serve

```
http://localhost:5555/plotting.jl
```

results in:

```
This webpage is not available
ERR_CONNECTION_REFUSED
```

```
julia runtests.jl
```

in  ~/.julia/Escher/bin/escher/test results in:

```
ERROR: test1 not defined
 in include at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/mac/.julia/Escher/test/macros.jl, in expression starting on line 5
while loading /Users/mac/.julia/Escher/test/runtests.jl, in expression starting on line 4
```

I am running OSX, using Julia Version 0.3.9 (2015-05-30 11:24 UTC).

**Comment by shashi** [comment]
What does running `/usr/bin/env julia` print in your terminal?

**Comment by shashi** [comment]
On OSX you can run this from the Julia REPL to serve:

```julia
julia> using Escher
julia> cd(Pkg.dir("Escher", "examples"))
julia> escher_serve()
```

**Comment by maacl** [comment]
/usr/bin/env julia

produces:

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.9 (2015-05-30 11:24 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

**Comment by maacl** [comment]
Following the above I get:

```
julia> using Escher

julia> cd(Pkg.dir("Escher", "examples"))

julia> escher_serve()
ERROR: escher_serve not defined
```

**Comment by maacl** [comment]
This might be related to how I am trying running julia from the terminal.

I have only symlinked the julia executable from to ```usr/local/bin```:

    ln -s /Applications/Julia-0.3.9.app/Contents/Resources/julia/bin/julia /usr/local/bin/

Do I need to do something more?

**Comment by shashi** [comment]
My bad, it should have been

`Escher.escher_serve()`

No your julia binary seems to be in the right place. How long did you wait before deciding `escher --serve` does not work? it usually takes about a minute for the server to start up. (JIT compilation of dependencies)

**Comment by maacl** [comment]
julia> Escher.escher_serve()
ERROR: escher_serve not defined

Autocomplete also does not reveal any Escher.escher_serve() function.

**Comment by shashi** [comment]
Oh, well. It should have been:

 ```julia
julia> using Escher
julia> include(Pkg.dir("Escher", "src", "cli", "serve.jl"))
julia> cd(Pkg.dir("Escher", "examples")) # or any other directory
julia> escher_serve()
```
My bad again :{

**Comment by maacl** [comment]
I just nuked my julia install and started over. There is no escher_serve() function in the Escher package.

**Comment by shashi** [comment]
The code shown above worked for me on Linux and Mac... Could you verify again?

**Comment by shashi** [comment]
I could not reproduce this on OSX. reopen if problem persists.
