### ISSUE TITLE
Would this be a good candidate for inclusion in JuliaWeb?

### ISSUE THREAD

**Issue by sbromberger** [shashi/Escher.jl#34]
If you think it's appropriate, I'd be happy to help transfer it (and make you a contributor, of course). Let me know. This looks like an absolutely wonderful package.

**Comment by Ismael-VC** [comment]
:+1:

**Comment by waldyrious** [comment]
:+1:

**Comment by randyzwitch** [comment]
I think it's a good idea, so that we can keep up momentum and work through the backlog of issues. A lot of the issues here are around design and could use decisions (or closing).

I'm toying with the idea of re-writing Julia Bloggers to use Escher, so I'm willing to put the time in.

**Comment by r2dbg** [comment]
Definitely - Escher has lost a lot of momentum since last summer, despite being one of the most powerful and unique libraries in METADATA.

**Comment by randyzwitch** [comment]
Going to close this...@shashi made me a collaborator to hopefully get the momentum going again. On reflection, JuliaWeb itself doesn't really generate a ton of movement, so it doesn't seem like much is gained moving the package that way
