### ISSUE TITLE
Load error after include(Pkg.dir("Escher", "src", "cli", "serve.jl"))

### ISSUE THREAD

**Issue by dbrowne** [shashi/Escher.jl#35]
Version 0.4.0-dev+5293 (2015-06-10 09:21 UTC)
julia> using Escher
Warning: New definition 
    serialize(Any, DataStructures.HashDict) at /apps/infrafs1/dbrowne/.julia/v0.4/DataStructures/src/hashdict.jl:91
is ambiguous with: 
    serialize(Base.SerializationState, Any) at serialize.jl:399.
To fix, define 
    serialize(Base.SerializationState, DataStructures.HashDict)
before the new definition.
Warning: New definition 
    serialize(Any, DataStructures.HashDict) at /apps/infrafs1/dbrowne/.julia/v0.4/DataStructures/src/hashdict.jl:91
is ambiguous with: 
    serialize(Base.IO, Any) at serialize.jl:421.
To fix, define 
    serialize(Base.IO, DataStructures.HashDict)
before the new definition.
Warning: New definition 
    deserialize(Any, Type{DataStructures.HashDict{#K<:Any, #V<:Any, #O<:Any}}) at /apps/infrafs1/dbrowne/.julia/v0.4/DataStructures/src/hashdict.jl:100
is ambiguous with: 
    deserialize(Base.SerializationState, DataType) at serialize.jl:653.
To fix, define 
    deserialize(Base.SerializationState, Type{DataStructures.HashDict{#K<:Any, #V<:Any, #O<:Any}})
before the new definition.

julia> include(Pkg.dir("Escher", "src", "cli", "serve.jl"))
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: Range1 not defined
 in include at ./boot.jl:253
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in require at /apps/infrafs1/dbrowne/.julia/v0.4/Requires/src/require.jl:8
 in include at ./boot.jl:253
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in require at /apps/infrafs1/dbrowne/.julia/v0.4/Requires/src/require.jl:8
 in include at ./boot.jl:253
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
 in require at /apps/infrafs1/dbrowne/.julia/v0.4/Requires/src/require.jl:8
 in include at ./boot.jl:253
 in include_from_node1 at ./loading.jl:133
while loading /apps/infrafs1/dbrowne/.julia/v0.4/Lazy/src/Lazy.jl, in expression starting on line 106
while loading /apps/infrafs1/dbrowne/.julia/v0.4/Hiccup/src/Hiccup.jl, in expression starting on line 3
while loading /apps/infrafs1/dbrowne/.julia/v0.4/Mux/src/Mux.jl, in expression starting on line 20
while loading /apps/infrafs1/dbrowne/.julia/v0.4/Escher/src/cli/serve.jl, in expression starting on line 5

julia>

**Comment by aviks** [comment]
This is a Lazy.jl issue on `v0.4`

Doing a `Pkg.checkout("Lazy")`  should fix this particular problem.

**Comment by dbrowne** [comment]
Does not fix the problem .

**Comment by shashi** [comment]
Escher currently does not run on v0.4, after Lazy is checked out, GnuTLS causes trouble https://github.com/JuliaWeb/GnuTLS.jl/issues/45

**Comment by shashi** [comment]
Defer to #36
