### ISSUE TITLE
pages confuses layout

### ISSUE THREAD

**Issue by wkearn** [shashi/Escher.jl#37]
```julia
function main(window)
    push!(window.assets,"layout2")
    A = vbox(md"Hello, world!"|>
             fontcolor("#FFFFFF")|>
             pad(1em)|>
             fillcolor("#006699"),
             md"Howdy!"|>
             fontcolor("#FFFFFF")|>
             pad(1em)|>
             fillcolor("#669933")
             )
end
```
does what I  expect it to do. There are two boxes on top of each other, a blue one which says, "Hello, world!" and a green one which says "Howdy!"

However, say you want to make this layout the first page of a set of pages:
```julia
function main(window)
    push!(window.assets,"layout2")
    A = vbox(md"Hello, world!"|>
             pad(1em)|>
             fillcolor("#006699"),
             md"Howdy!"|>
             pad(1em)|>
             fillcolor("#669933")
             )
    pages([A])
end
```
This collapses the boxes and puts them on top of each other. The text ends up hanging outside the boxes.

Maybe I'm not understanding something about how `pages` works, but it seems like you should be able to use the layout API on individual pages.

Let me know if I can fix something easily, or if we just need more docs about higher-order layouts.

**Comment by shashi** [comment]
Thanks!
