### ISSUE TITLE
setup_transport not defined

### ISSUE THREAD

**Issue by heckdevice** [shashi/Escher.jl#47]
Getting the following error with Julia 0.3.0-rc3+8 when trying to include using include(Pkg.dir("Escher", "src", "cli", "serve.jl")) 

ERROR: setup_transport not defined
 in include at /Applications/Julia-0.3.0-rc3-14654867cf.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.0-rc3-14654867cf.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading --- .julia/v0.3/Escher/src/cli/serve.jl, in expression starting on line 80

I did checkout the latest as well using Pkg.checkout("Escher")

**Comment by shashi** [comment]
Can you check out master and try again?

**Comment by heckdevice** [comment]
Thanks a ton!!! Atleast the serve function is working now but i am getting a new set of errors... not sure if i've setup something wrong..

I've put the hello.jl file in the cli folder, same level where serve.jl is but the browser is throwing the following error:

resolve_asset not defined
 in setup_socket at /Users/shpant/.julia/v0.3/Escher/src/cli/serve.jl:47
 in anonymous at /Users/shpant/.julia/v0.3/Escher/src/cli/serve.jl:211
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:15
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:8
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:15
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:8
 in toresponse at /Users/shpant/.julia/v0.3/Mux/src/basics.jl:47
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:8
 in splitquery at /Users/shpant/.julia/v0.3/Mux/src/basics.jl:28
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:8
 in basiccatch at /Users/shpant/.julia/v0.3/Mux/src/basics.jl:78
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:8
 in todict at /Users/shpant/.julia/v0.3/Mux/src/basics.jl:21
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:12 (repeats 3 times)
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/Mux.jl:8
 in anonymous at /Users/shpant/.julia/v0.3/Mux/src/server.jl:29
 in on_message_complete at /Users/shpant/.julia/v0.3/HttpServer/src/HttpServer.jl:274
 in on_message_complete at /Users/shpant/.julia/v0.3/HttpServer/src/RequestParser.jl:107
 in http_parser_execute at /Users/shpant/.julia/v0.3/HttpParser/src/HttpParser.jl:106
 in add_data at /Users/shpant/.julia/v0.3/HttpServer/src/RequestParser.jl:156
 in process_client at /Users/shpant/.julia/v0.3/HttpServer/src/HttpServer.jl:238
 in anonymous at task.jl:340

**Comment by shashi** [comment]
What are the sequence of commands you are using to bring up the Escher server?

**Comment by heckdevice** [comment]
The same as mentioned in the site :

julia> using Escher
julia> include(Pkg.dir("Escher", "src", "cli", "serve.jl"))
julia> cd(Pkg.dir("Escher", "examples")) # or any other directory
julia> escher_serve()

**Comment by heckdevice** [comment]
This works with julia 0.3.10 distribution and latest Escher.

Thanks
