### ISSUE TITLE
Electron backend

### ISSUE THREAD

**Issue by ViralBShah** [shashi/Escher.jl#56]
I wonder if it is possible to have an Electron backend, as an alternative to the Polymer backend. Perhaps that will also make it possible to build rich desktop apps.

http://electron.atom.io/

Cc @keno @stefankarpinski

**Comment by shashi** [comment]
I don't think the Polymer bits need to go away. In fact it is required, Electron just provides the "web view" everything else has to be a traditionally made web app. cc @one-more-minute

**Comment by ViralBShah** [comment]
Thanks for the clarification.

**Comment by aviks** [comment]
Dup of #39 ?

**Comment by ViralBShah** [comment]
Seems so. Closing.
