### ISSUE TITLE
Open a Gitter chat room.

### ISSUE THREAD

**Issue by Ismael-VC** [shashi/Escher.jl#57]
Gitter/Github integration can be done by adding a Gitter badge to the `README.md`.

Example for one of my repos:

`[![Join the chat at https://gitter.im/Ismael-VC/HydrocarbonNets.jl](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Ismael-VC/HydrocarbonNets.jl?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)`

[![Join the chat at https://gitter.im/Ismael-VC/HydrocarbonNets.jl](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Ismael-VC/HydrocarbonNets.jl?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

This would allow us to have a good way to communicate and share stuff, it can be used with IRC also.

There are a lot of examples already: https://gitter.im/explore/tags/julia

**Comment by Ismael-VC** [comment]
![captura de pantalla 2015-07-31 a las 12 54 57](https://cloud.githubusercontent.com/assets/4594825/9013734/746541fc-3783-11e5-9f2a-15435c5b1210.png)

It also has coverage and CI integration.

**Comment by shashi** [comment]
Done.
