### ISSUE TITLE
Input field initialization fails, causing empty signal from forms. 

### ISSUE THREAD

**Issue by mdcfrancis** [shashi/Escher.jl#58]
Given the following watch! definition, where s is a sample().

    watch!(s, textinput( "Initial Value" , name = "field0", label = string( "Enter field0")))

the sampler fails to get the initial value, tracing this through  

    // Line 22 behavior.html 
    // initialize
    this.value = elem[self.attr] || elem.getAttribute(self.attr)

On an input field 'elem' references the outer paper-input-decorator and not the input field,

    <paper-input-decorator is="undefined">
        <input is="core-input" name="line0" id="line0">
        <watch-state is="undefined"></watch-state>
    </paper-input-decorator>

When the signal is sampled the result is an empty value unless the user has updated the field. As a kludge the following works, but is assuming that the first element is the input field. 

    this.value = elem[self.attr] || elem.getAttribute(self.attr)
            || elem.firstChild && ( elem.firstChild[self.attr] 
                || elem.firstChild.getAttribute(self.attr) )

**Comment by shashi** [comment]
This has been fixed.

```julia
function main(window)
    push!(window.assets, "widgets")
    s = sampler()
    inp = Signal(Dict())
    intent(s,
        vbox(
            watch!(s, :txt, textinput( "Initial Value", label = "Enter field0")),
            trigger!(s, :btn, button("send")),
            inp
        ),
    ) >>> inp
end
```
(note: has API chanes), works fine with the Initial Value.
