### ISSUE TITLE
Styles not applied on Firefox

### ISSUE THREAD

**Issue by aviks** [shashi/Escher.jl#6]
After setting the `webcomponents` config in Firefox, pages load correctly. However, the styles are not applied correctly.  Screenshots below. 

### Chrome 41.0.2272.104

![chrome](https://cloud.githubusercontent.com/assets/378918/6885264/ec79bda6-d60f-11e4-8f33-c084c8bfcb05.png)

### Firefox 36.0.1
![firefox](https://cloud.githubusercontent.com/assets/378918/6885265/fd08cc52-d60f-11e4-993b-a4d5105c3ff6.png)

**Comment by shashi** [comment]
This is better now. But the pages disappear... Also plotting has the same issue you were facing. Firefox has a bug with its WebSocket inspector, I think. I cannot see what is getting transferred, but it seems to be getting transferred anyway.

**Comment by randyzwitch** [comment]
@aviks or @shashi, is this still an issue? I have some time to mark and cleanup the issues...

If I don't hear back by end of the week, I'll close.
