### ISSUE TITLE
Dynamic layouts

### ISSUE THREAD

**Issue by mturok** [shashi/Escher.jl#71]
@shashi :   I was wondering if there are any example of truly dynamic layouts?

For example, do you have an example of some callback that would add a new tab?

In a further step down this road, do you have any thoughts on how to integrate something like a gridstack-like drag/drop capability: http://troolee.github.io/gridstack.js/

In that case, not sure if julia would owns the layout model.

(BTW I see that polymer has some core-drag-drop capability, but the dynamic layout from gridstack is a bit more interesting -  https://www.polymer-project.org/0.5/docs/elements/core-drag-drop.html)

Thanks,
Michael

**Comment by shashi** [comment]
There are two feasible approaches, one is using JS layout engines like Gridstack, and another is using Julia with JuMP solving for optimal layouts here's [a paper on this](http://dl.acm.org/citation.cfm?id=2379268&dl=ACM&coll=DL&CFID=727243755&CFTOKEN=26376641).
