### ISSUE TITLE
Can't access a local svg image

### ISSUE THREAD

**Issue by pabloferz** [shashi/Escher.jl#81]
I've tried to add an svg in different ways but I can't find I way to make it display. For instance,

```julia
Elem{:object, :object}({:data=>"image.svg", :type=>"image/svg+xml"}, EmptyNode)
```
or
```julia
Elem{:img, :img}({:src=>"image.svg"}, EmptyNode)
```

do not work

**Comment by shashi** [comment]
You can construct SVG with Elems like this:

```julia
                mkcircle(x, y, r, color="lightgrey") =
                    Elem(:svg, :circle,
                        cx=x, cy=y, r=r,
                        style=[:fill => color],
                    )

                Elem(:svg, :svg, [
                    mkcircle(100, 100, 50),
                    mkcircle(100, 200, 70),
                    mkcircle(100, 100, 10, "orange"),
                    mkcircle(80, 80, 10, "white"),
                    mkcircle(120, 80, 10, "white"),
                 ], width=500px, height=500px)
```

Could you try `Elem(:object, attributes={:data=>"/assets/image.svg", :type=>"image/svg+xml"})` ?

This will work only if image.svg is in the assets directory.

If you want to read in an image from disk, you could try:

`Elem(:div, innerHTML="$(readall("image.svg"))")`

**Comment by pabloferz** [comment]
I want to read a local SVG image. 

```julia
Elem(:div, innerHTML="$(readall("image.svg"))")
```

loads the image, but then I can't find a way to scale it.

Because of the way SVGs are handled and one can't use `Images` to load them, I think a tile for them would be really useful.

**Comment by pabloferz** [comment]
```julia
Elem(:img, attributes={:src=>"/assets/image.svg", :width=>300})
```

also works, and scales the image, but I find it very inconvenient to have to put the images in the assests derectory.

**Comment by shashi** [comment]
There is a way if you put the image in an `assets/` folder in your own Julai package. See #74 for details on how to get this to work.

Admittedly, the asset serving needs a better framework.

**Comment by pabloferz** [comment]
I tried another workaround. I modified the `escher_serve` function adding this line

```julia
route("source", Mux.files(dir), Mux.notfound()),
```

to the `static` `App`. Now I can access the files in the path of the source julia file by going to `source/`.

Does that represents an issue from the some point of view (security or another reason)?

**Comment by shashi** [comment]
No it does not. I would call it "assets" for consistency.

**Comment by pabloferz** [comment]
Wouldn't that interfere with the line `route("assets", Mux.files(Pkg.dir("Escher", "assets")), Mux.notfound()),` or it doesn't matter?

**Comment by pabloferz** [comment]
Maybe `src/assets`? If that's OK, would you mind if a send a PR proposing the addition of this feature?

**Comment by shashi** [comment]
`assets/` is more convenient and consistent with the other features. Sure, I'd merge that. :)

**Comment by pabloferz** [comment]
The problem is that `assets` is already assigned by `route("assets", Mux.files(Pkg.dir("Escher", "assets")), Mux.notfound()),` to get access to the `Escher/assets` directory.

The two options I think might work are:

- To change the current `assets` to `escher/assets` (this is only used internally as far as I can see) and then add `assets` as proposed above.
- Leave `assets` as is, and add something like `user/assets`.

Which seems better to you?
