### ISSUE TITLE
0.4 deprecations break functionality in Escher 

### ISSUE THREAD

**Issue by mdcfrancis** [shashi/Escher.jl#87]
https://github.com/shashi/Escher.jl/commit/87975dc64ad118afd405c53bed6404e07f1db9c6#commitcomment-13263356

**Comment by mdcfrancis** [comment]
```
f( arg::Array ) = println( arg )
f( arg... ) = f( collect( arg))
f( arg ) = f( [arg] )

f( "hello" )
f( ["hello","world"])
f( "hello", "world")

```

Actually why was this changed in the first place ? I don't see and deprecation warnings here.

**Comment by shashi** [comment]
@mdcfrancis what about `f( ("hello", "world") )`

**Comment by shashi** [comment]
fix incoming

**Comment by mdcfrancis** [comment]
Thanks
