### ISSUE TITLE
Example of Keypress

### ISSUE THREAD

**Issue by mturok** [shashi/Escher.jl#92]
Hi Shashi,

Any example of keypress behaviors?

Thanks,
Michael

**Comment by shashi** [comment]
Simple example: https://github.com/shashi/Escher.jl/blob/master/examples/keypress.jl
Using keypress to trigger other updates: https://github.com/shashi/Escher.jl/blob/master/examples/code-cell.jl

**Comment by mturok** [comment]
Thank you! Will try immediately.

**Comment by shashi** [comment]
Allowed key combinations are described at the end of: https://elements.polymer-project.org/elements/iron-a11y-keys
the Key type is here: https://github.com/shashi/Escher.jl/blob/master/src/basics/behavior.jl#L61-L67
