### ISSUE TITLE
List comprehension on radiogroup

### ISSUE THREAD

**Issue by raghuch** [shashi/Escher.jl#95]
The radiogroup takes in a list of radio buttons. When I try to declare a list of radio buttons in a list comprehension i.e.
``` 
radiogroup([radio("i", "$i") for i in 1:5]   )
```
I get a radio group which doesn't allow me to select only one button. The first button (with tag '1') is selected always, whenever I click on any other radio button.

Is this an unintended bug or can't we use list comprehensions in radiogroup?

**Comment by randyzwitch** [comment]
At this point, this is a year old. Is this still an issue @raghuch, or have you move on / is it resolved?
