### ISSUE TITLE
examples depend pkgs not in REQUIRE, Gadlfly and Compose

### ISSUE THREAD

**Issue by ggggggggg** [shashi/Escher.jl#98]
The title pretty much says it, it seems like the packages necessary to use the examples should be in REQUIRE.

**Comment by randyzwitch** [comment]
In the spirit of clean-up, closing this. As a personal opinion, I don't think it's the intent to have optional packages being part of REQUIRE; you could always not use the examples (for example, I only use Vega and not Gadfly, if only because I'm developing Vega).
