### ISSUE TITLE
plotting.jl fails due to UndefVarError: inch not defined

### ISSUE THREAD

**Issue by ggggggggg** [shashi/Escher.jl#99]
I'm running `v0.4.0` on OSX. I ran `escher --serve` in the examples directory and pointed my browser at `http://localhost:5555/plotting.jl`. In the browser I get `UndefVarError: inch not defined` and a long traceback. In the console I get another traceback, and I think they key line is

```
WARNING: both Gadfly and Escher export "inch"; uses of it in module Main must be qualified
```

**Comment by ggggggggg** [comment]
`code-cell.jl` has a similar issue with sampler, again I think the key line is `WARNING: both Distributions and Escher export "sampler"; uses of it in module Main must be qualified`

**Comment by randyzwitch** [comment]
Related #41 (Seems like a meta-issue might be needed for qualifying namespaces)

**Comment by randyzwitch** [comment]
Closing in favor of #137
